openapi: 3.0.3
info:
  x-openapi-id: glstat-oas3-api-entities_1_4_0
  title: GBO Entities
  x-ibm-name: gbo-entities
  version: 1.4.0
  description: |
    It allows the possibility of standardizing the way entities are created and
    generated for the different regions and global entities of GBO (Global Backoffice), allowing the
    creation of entities in a single way for the different users with a new way
    that allows this action to be carried out.
  termsOfService: https://internal-apimarket.scib.gs.corp/scib/internal/terms
  contact:
    url: https://confluence.alm.europe.cloudcenter.corp/display/CIBMARKBO/cib_markbo+Home
    name: Dario Vega Sánchez
    email: dario.vega@gruposantander.com
  license:
    name: Santander CIB API License
    url: https://internal-apimarket.scib.gs.corp/scib/internal/terms
  x-santander-catalogation:
    bian-landscape-version: 11
    bian-business-area: Reference Data
    bian-business-domain: Party
    bian-service-domain: Legal Entity Directory
  x-entity-catalogation:
    entity: SCIB Global
    business-domain: MARKETS
    business-area: Markets Back-office
    functional-application-name: GBO Global
    functional-application-id: 6599
  x-api-governance:
    type: LEGACY
    is-api-compliance: true
externalDocs:
  description: Find more information here.
  url: https://confluence.alm.europe.cloudcenter.corp/display/CIBMARKBO/cib_markbo+Home
servers:
  - url: /v1/gbo_entities
tags:
  - name: Entities
    description: Operations related to entities.
  - name: Account Owners
    description: Operations related to account owners.
  - name: Liveness / Readiness
    description: Operations related to the liveness and readiness of the service.
paths:
  /entities:
    parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/X-Santander-Client-Id'
      - $ref: '#/components/parameters/X-Santander-Device'
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/If-Match'
      - $ref: '#/components/parameters/X-B3-TraceId'
      - $ref: '#/components/parameters/X-B3-ParentSpanId'
      - $ref: '#/components/parameters/X-B3-SpanId'
      - $ref: '#/components/parameters/X-B3-Sampled'
    get:
      summary: Retrieves operational entities.
      description: Retrieves operational entities filtering by GLCS (Global Limit Code System).
      operationId: retrieveEntities
      tags:
        - Entities
      parameters:
        - $ref: '#/components/parameters/Entity-Glcs'
        - $ref: '#/components/parameters/Markit-Entity-Identifier'
        - $ref: '#/components/parameters/Legal-Entity-Identifier'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveEntityInformation'
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
    post:
      summary: Creates an operational entity.
      description: Creates an operational entity.
      operationId: createEntities
      tags:
        - Entities
      requestBody:
        $ref: '#/components/requestBodies/CreateEntity'
      responses:
        '200':
          $ref: '#/components/responses/CreateEntity'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
  /entities/{entity_id}:
    parameters:
      - $ref: '#/components/parameters/Entity-Id'
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/X-Santander-Client-Id'
      - $ref: '#/components/parameters/X-Santander-Device'
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/If-Match'
      - $ref: '#/components/parameters/X-B3-TraceId'
      - $ref: '#/components/parameters/X-B3-ParentSpanId'
      - $ref: '#/components/parameters/X-B3-SpanId'
      - $ref: '#/components/parameters/X-B3-Sampled'
    patch:
      summary: Updates an operational entity.
      description: Updates an operational entity.
      operationId: updateEntities
      tags:
        - Entities
      requestBody:
        $ref: '#/components/requestBodies/UpdateEntity'
      responses:
        '200':
          $ref: '#/components/responses/UpdateEntity'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
  /entities/{entity_id}/account_owners:
    parameters:
      - $ref: '#/components/parameters/Entity-Id'
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/X-Santander-Client-Id'
      - $ref: '#/components/parameters/X-Santander-Device'
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/If-Match'
      - $ref: '#/components/parameters/X-B3-TraceId'
      - $ref: '#/components/parameters/X-B3-ParentSpanId'
      - $ref: '#/components/parameters/X-B3-SpanId'
      - $ref: '#/components/parameters/X-B3-Sampled'
    post:
      summary: Creates account owners associated with an entity.
      description: Creates account owners associated with an entity.
      operationId: createAccountOwners
      tags:
        - Account Owners
      requestBody:
        $ref: '#/components/requestBodies/CreateAccountOwner'
      responses:
        '201':
          $ref: '#/components/responses/CreateAccountOwner'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
    patch:
      summary: Updates account owners associated with an entity.
      description: Updates account owners associated with an entity.
      operationId: updateAccountOwners
      tags:
        - Account Owners
      requestBody:
        $ref: '#/components/requestBodies/UpdateAccountOwner'
      responses:
        '200':
          $ref: '#/components/responses/UpdateAccountOwner'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
  /health:
    parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/X-Santander-Client-Id'
      - $ref: '#/components/parameters/X-Santander-Device'
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/If-None-Match'
      - $ref: '#/components/parameters/If-Match'
      - $ref: '#/components/parameters/X-B3-TraceId'
      - $ref: '#/components/parameters/X-B3-ParentSpanId'
      - $ref: '#/components/parameters/X-B3-SpanId'
      - $ref: '#/components/parameters/X-B3-Sampled'
    get:
      summary: Retrieve the liveness and the readiness of the service.
      description: Retrieve the liveness and the readiness of the service.
      tags:
        - Liveness / Readiness
      operationId: retrieveHealth
      responses:
        '200':
          $ref: '#/components/responses/RetrieveHealth'
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
components:
  schemas:
    Entity:
      description: Data structure containing information about an entity
      type: object
      minProperties: 1
      properties:
        id:
          type: number
          description: Unique identifier of the operational entity.
          readOnly: true
          example: 123.28
        glcs:
          type: string
          description: GLCS (Global Limit Code System). Internal and global unique reference of the Legal Entity.
          readOnly: true
          example: UAT1
        name:
          type: string
          description: Full name of the Entity.
          example: Beijing Branch
        type:
          type: object
          description: Data structure containing information about an entity type.
          required:
            - code
            - name
          properties:
            code:
              type: string
              description: |
                Entity type Code:
                - COM: Company
                - GOV: Government
                - IND: Individual
                - SUP: Supranational
              enum:
                - COM
                - GOV
                - IND
                - SUP
              example: COM
            name:
              type: string
              description: Entity type name.
              readOnly: true
              example: Company
        industry:
          type: object
          description: Data structure containing information about an entity industry.
          required:
            - code
            - name
          properties:
            code:
              type: string
              description: |
                Industry code. Possible values are:
                - BANSB: Banks & Saving Banks
                - BROKE: Brokers
                - CLIEN: Clients
                - CORPN: Companies
                - CORPC: Corporate Classified
                - EQUIS: Fund Managers, Operating Unit
                - FUNMA: Funds, Operating Unit
                - HDFND: Hedge Funds
                - INSUR: Insurance
                - ORGMA: Organized Markets
                - CARDH: Other Financial Entities
                - PROJE: Project Finance
                - PUBIN: Public Institutions
                - SOVER: Sovereign
                - SUPRA: Supranational Entities
                - SECUR: Securitizations (Titulizaciones)
              enum:
                - BANSB
                - BROKE
                - CLIEN
                - CORPN
                - CORPC
                - EQUIS
                - FUNMA
                - HDFND
                - INSUR
                - ORGMA
                - CARDH
                - PROJE
                - PUBIN
                - SOVER
                - SUPRA
                - SECUR
              example: CORPN
            name:
              type: string
              description: Industry name.
              readOnly: true
              example: Clients
        residenceCountry:
          $ref: '#/components/schemas/Country'
        bookingUnit:
          $ref: '#/components/schemas/BookingUnit'
        status:
          type: string
          description: Entity status.
          enum:
            - ACTIVE
            - INACTIVE
            - DISABLED
          example: ACTIVE
        localAliases:
          type: array
          description: List of local identifiers for a given operational entity.
          items:
            description: 'Data structure containing information about a local identifier'
            allOf:
              - $ref: '#/components/schemas/Identifier'
        externalAliases:
          type: array
          description: List of external identifiers for a given operational entity.
          items:
            description: 'Data structure containing information about an external identifier of the Entity. It should be used when more than one Entity has the same code in a given system. For example, it should be used to identify the Fund Manager of a given Fund, which is setup as an Entity.'
            allOf:
              - $ref: '#/components/schemas/Identifier'
        tradingAccountIdentifiers:
          type: array
          description: List of Trading Account Identifiers.
          items:
            $ref: '#/components/schemas/TradingAccountIdentifier'
        sourceApplication:
          type: object
          description: Data structure containing information about a source application.
          required:
            - code
            - name
          properties:
            code:
              type: string
              description: Source system code.
              example: KYCCM
            name:
              type: string
              description: Source system name.
              readOnly: true
              example: KYC Case Manager
        owner:
          $ref: '#/components/schemas/Owner'
        document:
          $ref: '#/components/schemas/Document'
        legalEntityIdentifier:
          type: string
          description: Legal Entity Identifier (LEI). It is a unique global identifier of legal entities participating in financial transactions.
          example: '00000000001234567890'
        riskSegmentation:
          type: object
          description: Data structure containing information about risk segmentation of the entity
          required:
            - riskSegment
            - riskSector
          properties:
            riskSegment:
              $ref: '#/components/schemas/RiskSegment'
            riskSector:
              $ref: '#/components/schemas/RiskSector'
        amlRiskClassification:
          type: string
          description: Anti-Money Laundering (AML) risk classification
          enum:
            - LOW
            - MEDIUM
            - HIGH
          example: MEDIUM
        globalRegulatoryIndicators:
          type: object
          description: |
            Data structure containing information about global regulations:
            - European Market Infrastructure Regulation (EMIR)
            - Dodd-Frank Wall Street Reform and Consumer Protection Act (DFA)
          minProperties: 1
          properties:
            emir:
              $ref: '#/components/schemas/Emir'
            dfa:
              $ref: '#/components/schemas/Dfa'
        mifid:
          $ref: '#/components/schemas/Mifid'
        roles:
          type: array
          description: List of entity roles
          items:
            $ref: '#/components/schemas/WrapperEntityRole'
        globalSector:
          $ref: '#/components/schemas/GlobalSector'
        operationalBranches:
          type: array
          description: List of operational branches the entity can operate on.
          items:
            $ref: '#/components/schemas/OperationalBranch'
        postalAddress:
          $ref: '#/components/schemas/PostalAddress'
        markitEntityIdentifier:
          type: string
          description: Markit Entity Identifier (MEI). It's a unique 10-digit code issued to distinctly identify legal entities in the loan market, including banks, buy-side institutions, custodians, trustees and corporate borrowers.
          example: '00123456D'
        relationships:
          $ref: '#/components/schemas/Relationships'
        localProperties:
          type: array
          description: List of local properties of the entity for a given country
          items:
            $ref: '#/components/schemas/LocalProperties'
    LocalProperties:
      type: object
      description: Data structure containing information about local properties of the entity for a given country
      required:
        - country
      properties:
        country:
          $ref: '#/components/schemas/Country'
        properties:
          type: array
          description: List of properties
          items:
            $ref: '#/components/schemas/Variables'
    Relationships:
      type: object
      description: Data structure containing information about an entity relationships
      minProperties: 1
      properties:
        entities:
          type: array
          description: List of related entities
          items:
            $ref: '#/components/schemas/Relationship'
    Relationship:
      type: object
      description: Data structure containing information about the relationship of an entity
      required:
        - identifier
        - relationshipTypeCode
      properties:
        identifier:
          $ref: '#/components/schemas/Identifier'
        relationshipTypeCode:
          type: string
          description: "Code for the related entity's relationship type"
          example: 'BRANCH'
        relationshipTypeDescription:
          type: string
          description: "Description of the related entity's relationship type"
          example: 'Has a branch'
          readOnly: true
    Owner:
      type: object
      description: Data structure containing information about an owner Entity. Indicates the Business Unit / Santander Legal Entity that owns the financial relationship with the Client. Information captured as part of the onboarding process.
      required:
        - code
      properties:
        code:
          type: string
          description: |
            Owner Code. Possible values are:
            - BS: Boadilla
            - ED: Spain
            - FD: Frankfurt
            - HF: Hong-Kong
            - MF: Milan
            - PD: Paris
            - 9N: Santander Bank National Association
            - 9J: Santander Beijing
            - 9B: Santander Brazil
            - 9C: Santander Chile
            - 9O: Santander Colombia
            - SG: Santander Global Branch
            - SL: Santander London Branch
            - 9M: Santander Mexico
            - MI: Santander Miami
            - NY: Santander NY
            - 9E: Santander Peru
            - 9P: Santander Poland
            - 9G: Santander Portugal
            - 9R: Santander Rio
            - IS: Santander SIS
            - 9S: Santander Shanghai
            - SU: Santander UK
            - 9U: Santander Uruguay
            - SF: Singapore
          enum:
            - BS
            - ED
            - FD
            - HF
            - MF
            - PD
            - 9N
            - 9J
            - 9B
            - 9C
            - 9O
            - SG
            - SL
            - 9M
            - MI
            - NY
            - 9E
            - 9P
            - 9G
            - 9R
            - IS
            - 9S
            - SU
            - 9U
            - SF
          example: SF
        description:
          type: string
          description: Owner description
          readOnly: true
          example: Singapore
    Document:
      description: 'Data structure containing information about an identification document for a person or an organization'
      type: object
      required:
        - documentNumber
        - documentTypeCode
      properties:
        documentNumber:
          type: string
          description: 'Document number'
          example: '50456713W'
        documentTypeCode:
          type: string
          description: |
            Document type code. Possible values are:
            - SSN: SOCIAL SECURITY NUMBER
            - EIN: EMPLOYER IDENTIFICATION NUMBER
            - TAX_ID: Tax ID
            - UNDEF: Undefined
            - AEI: Applied For EIN
            - BSC: BUSINESS CERTIFICATE/ARTICLES
            - IBN: IBAN - International Bank Account Number
            - ISN: ISIN - INTERNATIONAL SECURITIES IDENTIFICATION NUMBER
          enum:
            - SSN
            - EIN
            - TAX_ID
            - UNDEF
            - AEI
            - BSC
            - IBN
            - ISN
          example: 'ISN'
        documentTypeDescription:
          type: string
          description: 'Document type description'
          readOnly: true
          example: 'ISIN - INTERNATIONAL SECURITIES IDENTIFICATION NUMBER'
    RiskSegment:
      type: object
      description: Data structure containing information about risk segment, also known as counterparty segment
      required:
        - code
      properties:
        code:
          type: string
          description: Risk segment code.
          example: CART
        description:
          type: string
          description: Risk segment description
          readOnly: true
          example: CARTERIZADOS
    RiskSector:
      type: object
      description: Data structure containing information about risk classification based on the entity activity/business, also known as counterparty sector
      required:
        - code
      properties:
        code:
          type: string
          description: Risk sector code.
          example: PF
        description:
          type: string
          description: Risk Sector Description
          example: PERSONAS FISICAS
          readOnly: true
    Emir:
      type: object
      description: Data structure containing European Market Infrastructure Regulation (EMIR)
      required:
        - classificationDate
        - crdClearingObligationCategory
      properties:
        classificationDate:
          type: string
          description: "Date when the classification of EMIR Source Class was done.\n\nThe value uses the complete data format defined in ISO 8601:\n\n'YYYY-MM-DD'\n\nWhere:\n- YYYY: 4-digit year\n- MM: 2-digit month (for example, 01 = January)\n- DD: 2-digit day of the month (01 through 31)"
          format: date
          example: '2022-03-02'
        crdClearingObligationCategory:
          type: string
          description: |
            Clearing obligation category of the entity for Credit Derivatives (CRD) contracts. Possible values are:
            - CAT_1: Category 1
            - CAT_2: Category 2
            - CAT_3: Category 3
            - CAT_4: Category 4
          enum:
            - CAT_1
            - CAT_2
            - CAT_3
            - CAT_4
          example: CAT_1
    Dfa:
      type: object
      description: Data structure containing Dodd-Frank Wall Street Reform and Consumer Protection Act (DFA)
      required:
        - ownershipType
      properties:
        ownershipType:
          type: object
          description: Data structure containing Dodd-Frank Wall Street Reform and Consumer Protection Act (DFA) Ownership type
          required:
            - code
          properties:
            code:
              type: string
              description: |
                DFA ownership type code. Possible values are:
                - NONUSCON: Non-US Affiliate Conduit
                - NONUSAFF: Non-US Affiliate of a US person guaranteed by a US Person
                - NONUSBR: Non-US Branch of US Swap Dealer
                - NONUSNY: Non-US Non-Swap Dealer Counterparty NY
                - NODFACOV: Non-DFA covered
                - OTHER: Other (any non-US Swap Dealer or Major Swap Participant)
                - USCPTYDOM: US Counterparty Domicile
              enum:
                - NONUSCON
                - NONUSAFF
                - NONUSBR
                - NONUSNY
                - NODFACOV
                - OTHER
                - USCPTYDOM
              example: USCPTYDOM
            description:
              type: string
              description: DFA ownership type description
              readOnly: true
              example: US Counterparty Domicile
        isEligibleContractParticipant:
          type: boolean
          description: Whether the entity is eligible to be a contract participant
          example: true
        eligibleContractParticipantTypes:
          type: array
          description: List of eligible contract participant types.
          items:
            $ref: '#/components/schemas/DfaEligibleContractParticipantType'
        hasStandingOptOutAnnualFiling:
          type: boolean
          description: "Whether the operation has a clearing exception, which is decided together with the election for DFA question 'Standing End-User Exception'"
          example: true
        isCoveredForexTransactions:
          type: boolean
          description: "Whether the counterparty has answered 'Yes' to the Questionnaire for Covered Forex Transactions"
          example: true
        isCoveredDerivativeTransactions:
          type: boolean
          description: "Whether the counterparty has answered 'Yes' to the Questionnaire for Covered Derivative Transactions"
          example: true
        isAdditionalPtmmTransactions:
          type: boolean
          description: "Whether the counterparty has answered 'Yes' to the Questionnaire for Additional Pre-Trade Mid-Market Marks (PTMM) Transactions"
          example: true
        hasOralDisclosurePtmmElection:
          type: boolean
          description: "Whether the Pre-Trade Mid-Market Marks (PTMM) can be provided to the counterparty orally prior to the execution. Even if the answer is 'Yes', the PTMM must also be provided in written format by the end of the day of execution."
          example: true
    DfaEligibleContractParticipantType:
      type: object
      description: Data structure containing DFA Eligible Contract Participant Type for the entity.
      required:
        - code
      properties:
        code:
          type: string
          description: |
            DFA Eligible Contract Participant Type Code. Possible values are:
            - APREGBR: Authorised Person of Registered Broker
            - ALTCOM: Alternative Commodity Pool
            - BRDEAT: Broker or Dealer is a Natural Person
            - BRDENONAT: Broker or Dealer is a Non-Natural Person
            - ELICOMMOD: Eligible Commodity Pool
            - ELIGOV: Eligible Government Entity
            - ELIINDIV: Eligible Individual
            - ELIINSUR: Eligible Insurance Company
            - ELIINVEST: Eligible Investment Company
            - EMPBENPLAN: Employee Benefits Plan
            - FCMNATPER: FCM (Futures Commission Merchant) is a Natural Person
            - FCMNONNAT: FCM (Futures Commission Merchant) is a Non-Natural Person
            - FINANENT: Financial Entity
            - FINANINST: Financial institution
            - FLOORBRTR: Floor Broker or Floor Trader
            - HEDGEECP: Hedging Entity ECP (Eligible Contract Participant)
            - HEDGIECP: Hedging Individual ECP (Eligible Contract Participant)
            - INVBANKHO: Investment Bank Holding Company
            - LARGEENT: Large Entity
            - MAJORSBP: Major Security-Based Swap Participant
            - MAJORSWAP: Major Swap Participant
            - OTHPERSON: Other Eligible Person
            - SBSWAP: Security-Based Swap Dealer
            - SPECIALENT: Special Entity
            - SWAPDEAL: Swap Dealer
          enum:
            - APREGBR
            - ALTCOM
            - BRDEAT
            - BRDENONAT
            - ELICOMMOD
            - ELIGOV
            - ELIINDIV
            - ELIINSUR
            - ELIINVEST
            - EMPBENPLAN
            - FCMNATPER
            - FCMNONNAT
            - FINANENT
            - FINANINST
            - FLOORBRTR
            - HEDGEECP
            - HEDGIECP
            - INVBANKHO
            - LARGEENT
            - MAJORSBP
            - MAJORSWAP
            - OTHPERSON
            - SBSWAP
            - SPECIALENT
            - SWAPDEAL
          example: APREGBR
        description:
          type: string
          description: Eligible Contract Participant Type Description
          readOnly: true
          example: AP of Registered Broker
    Mifid:
      type: object
      description: Data structure containing information about the Markets in Financial Instruments Directive (MiFID)
      required:
        - category
      properties:
        category:
          type: object
          description: Data structure containing category for MIFID regulation branch segregation
          required:
            - code
            - branch
          properties:
            code:
              type: string
              description: |
                MiFID category code. Possible values are:
                - CE: ELIGIBLE COUNTERPARTY (CONTRAPARTE ELEGIBLE)
                - ELGCP: ELIGIBLE COUNTERPARTY
                - MI: RETAIL (MINORISTA)
                - PF: PROFESIONAL PER SE
                - PROF: PROFESSIONAL
                - PS: ELECTIVE PROFESSIONAL (PROFESIONAL BAJO SOLICITUD)
                - RTL: RETAIL
              enum:
                - CE
                - ELGCP
                - MI
                - PF
                - PROF
                - PS
                - RTL
              example: 'PS'
            description:
              type: string
              description: MIFID Category description
              readOnly: true
              example: 'PROFESIONAL BAJO SOLICITUD'
            branch:
              $ref: '#/components/schemas/Branch'
    GlobalSector:
      type: object
      description: Data structure containing information about the Global Economic Sector. Used to indicate the economic activity code of the Entity. It is known as CNAE in Spain, CAE in Portugal, SIC in UK/US, etc.
      required:
        - code
      properties:
        code:
          type: string
          description: Indicate the economic activity code of the Entity
          example: '0112'
        description:
          type: string
          description: Global Sector description
          readOnly: true
          example: 'Rice cultivation'
    OperationalBranch:
      type: object
      description: Data structure containing an operational branch in which the customer can operate, and its Hold and Sub Hold, if any. Only the Madrid Real branch has Hold and Sub Hold configured, since this data comes from the granular Partenon segment.
      required:
        - branch
      properties:
        branch:
          $ref: '#/components/schemas/Branch'
        hold:
          $ref: '#/components/schemas/Hold'
        subHold:
          $ref: '#/components/schemas/SubHold'
        variables:
          type: array
          description: List of variables of the entity for the operational branch
          items:
            $ref: '#/components/schemas/Variables'
        localEntitySector:
          $ref: '#/components/schemas/LocalEntitySector'
    LocalEntitySector:
      type: object
      description: Data structure containing informatin about the sector assigned to a local entity according to local regulatory law.
      required:
        - code
      properties:
        code:
          type: string
          description: Code to Local Entity Sector
          example: '403'
        description:
          type: string
          description: Description to Local Entity Sector
          readOnly: true
          example: '403-Group Office - Insurance'
    Variables:
      type: object
      description: Data structure containing information about a variable field
      required:
        - label
        - value
      properties:
        label:
          type: string
          description: Field label
          example: 'ALLTR'
        typeDescription:
          type: string
          description: Field type description
          readOnly: true
          example: 'ALLOWED TO TRADE'
        value:
          type: string
          description: Field value
          example: 'True'
    SubHold:
      type: object
      description: Data structure containing information about a Sub hold. It is used to segment clients into smaller groups for better classification.
      required:
        - code
      properties:
        code:
          type: string
          description: Sub hold code
          example: 'IP'
        description:
          type: string
          description: Sub hold description
          readOnly: true
          example: 'PRIVATE INSTITUTIONS'
    Hold:
      type: object
      description: Data structure containing information about a Hold. It is used to classify clients, grouping those with a similar typology and knowing if a client belongs to Commercial Banking (retail) or Wholesale Banking. For example if they belong to PRIVATE BANKING, COMPANIES, PYMES, BUSINESSES or CORPORATE BANKING, etc.
      required:
        - code
      properties:
        code:
          type: string
          description: Hold code.
          example: 'PE'
        description:
          type: string
          description: Hold description
          readOnly: true
          example: 'PYMES'
    Branch:
      type: object
      description: Data structure containing information about a branch
      required:
        - code
      properties:
        id:
          type: number
          description: Branch identifier
          readOnly: true
          example: 20411.40
        code:
          type: string
          description: Branch code
          example: STDCH
        name:
          type: string
          description: Branch name
          readOnly: true
          example: BANCO SANTANDER CHILE
    PostalAddress:
      type: object
      description: Data structure containing information that locates and identifies a postal address
      required:
        - city
        - zipCode
        - country
        - state
        - streetName
      properties:
        city:
          $ref: '#/components/schemas/City'
        zipCode:
          type: string
          description: 'Address ZIP code'
          example: '02171'
        country:
          $ref: '#/components/schemas/Country'
        state:
          $ref: '#/components/schemas/State'
        streetName:
          type: string
          description: 'Name of a street or thoroughfare'
          example: 'Market St.'
    City:
      description: 'Data structure containing city information'
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 'City name'
          example: 'Houston'
          minLength: 0
          maxLength: 255
    State:
      description: 'Data structure containing state information'
      type: object
      required:
        - code
      properties:
        code:
          type: string
          description: "State code.\n\nThe value is based on the ISO 3166-2 (https://www.iso.org/obp/ui/#search/code/)."
          example: 'US-MA'
          minLength: 0
          maxLength: 30
        name:
          type: string
          description: 'State name'
          example: 'Massachusetts'
          minLength: 0
          maxLength: 255
          readOnly: true
    TradingAccountIdentifier:
      type: object
      description: Data structure containing Trading Account Identifier details.
      required:
        - type
        - id
        - creationDate
      properties:
        type:
          type: string
          description: |
            Type of Trading Account Identifier.
            - FDID: Firm Designated Identifier.
            - LTID: Large Trader Identifier.
          enum:
            - FDID
            - LTID
          example: FDID
        id:
          type: string
          description: Unique Identifier of the Trading Account assigned by SEC and provided by clearing house.
          example: 'PP9U3MXFJZX'
        creationDate:
          type: string
          format: date
          example: '2022-09-13'
          description: |
            Trading Account Identifier creation date.
            The value uses the complete data format defined in ISO 8601:\
            'YYYY-MM-DDThh:mm:ss.sssTZD'\
            Where:
            - YYYY: 4-digit year
            - MM: 2-digit month (for example, 01 = January)
            - DD: 2-digit day of the month (01 through 31).
    EntityRole:
      type: object
      description: Data structure containing role information that an Entity is (or was) allowed to perform with a particular Booking Unit, as well as the current status of each.
      required:
        - code
      properties:
        id:
          type: number
          description: Role identifier
          readOnly: true
          example: 23938.4
        code:
          type: string
          description: |
            Entity role code. Possible values are:
            - BRK: Broker
            - CDISS: Certificate of Deposit Issuer
            - CLE: Clearing
            - CLI: Client
            - CUS: Custody
            - GUA: Guarantor
            - ISS: Issuer
            - STK: Market
          enum:
            - BRK
            - CDISS
            - CLE
            - CLI
            - CUS
            - GUA
            - ISS
            - STK
          example: CLI
        description:
          type: string
          description: Role description
          readOnly: true
          example: Client
        status:
          $ref: '#/components/schemas/StatusInfo'
        bookingUnit:
          $ref: '#/components/schemas/BookingUnit'
    WrapperEntityRole:
      x-bizObjRef: EntityRole
      type: object
      description: Data structure containing role information that an Entity is (or was) allowed to perform with a particular Booking Unit, as well as the current status of each.
      required:
        - code
      properties:
        code:
          type: string
          description: |
            Entity role code. Possible values are:
            - BRK: Broker
            - CDISS: Certificate of Deposit Issuer
            - CLE: Clearing
            - CLI: Client
            - CUS: Custody
            - GUA: Guarantor
            - ISS: Issuer
            - STK: Market
          enum:
            - BRK
            - CDISS
            - CLE
            - CLI
            - CUS
            - GUA
            - ISS
            - STK
          example: CLI
        description:
          type: string
          description: Role description
          readOnly: true
          example: Client
    Product:
      type: object
      description: Data structure containing product information that an Entity with Client role is (or was) allowed to trade with a particular Booking Unit, as well as the current status of each.
      required:
        - code
      properties:
        id:
          type: number
          description: Product identifier
          readOnly: true
          example: 708.4
        code:
          type: string
          description: Product code
          example: 'BONDS & GUARANTEES'
        description:
          type: string
          description: Product description
          readOnly: true
          example: 'Bonds & Guarantees'
        status:
          $ref: '#/components/schemas/StatusInfo'
        bookingUnit:
          $ref: '#/components/schemas/BookingUnit'
    StatusInfo:
      description: "Data structure containing information about an item's status"
      type: object
      required:
        - statusCode
      properties:
        statusId:
          type: number
          description: 'Status ID'
          example: 7.66
          readOnly: true
        statusCode:
          type: string
          description: 'Status code'
          example: 'Active'
        statusDescription:
          type: string
          description: 'Status description'
          example: 'Active'
          readOnly: true
    BookingUnit:
      type: string
      description: Santander Bank Entity (Booking Unit) where the Entity is registered. This is used to route the creation.
      example: Santander Global Branch
    AccountOwner:
      description: Data structure containing information about an account owner. It is the relationship (Roles & Products) between an external entity (aka Counterparty), with a given Booking Entity (ex., Santander Chile, Santander Madrid).
      type: object
      minProperties: 1
      properties:
        id:
          type: number
          description: Unique identifier of the operational entity that's the owner of the account.
          readOnly: true
          example: 123.28
        glcs:
          type: string
          description: Global Limit Code System (GLCS). It is an internal and global unique reference of the counterpaty.
          readOnly: true
          example: UAT1
        products:
          type: array
          description: List of products.
          items:
            $ref: '#/components/schemas/Product'
        roles:
          type: array
          description: List of entity roles.
          items:
            $ref: '#/components/schemas/EntityRole'
    Country:
      description: Data structure containing country information based on the ISO 3166 (https://www.iso.org/obp/ui/#search/code/) standard.
      type: object
      required:
        - code
        - name
      properties:
        code:
          type: string
          description: Country ISO code (alfa-2)
          maxLength: 2
          example: ES
        name:
          type: string
          description: Country name
          readOnly: true
          example: SPAIN
    Identifier:
      type: object
      description: Data structure containing information about an identifier
      required:
        - code
        - value
      properties:
        code:
          type: string
          description: Code of the identifier
          example: 'FENERGO'
        value:
          type: string
          description: Identifier value
          example: '163681'
    Errors:
      description: Data structure containing the details for errors.
      type: object
      minProperties: 1
      properties:
        errors:
          type: array
          description: List of errors.
          items:
            $ref: '#/components/schemas/Error'
    Error:
      description: Data structure containing the error details.
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Unique alphanumeric human readable error code.
          example: badRequest
        message:
          type: string
          description: Brief summary of the reported issue.
          example: Message
        level:
          type: string
          description: Level of the reported issue.
          example: ERROR
          enum:
            - ERROR
            - FATAL
            - INFO
            - WARNING
        description:
          type: string
          description: Detailed description of the reported issue.
          example: Description
    Component:
      description: Data structure containing the status components.
      type: object
      required:
        - name
        - type
        - status
      properties:
        name:
          type: string
          description: Name of the component.
          example: Oracle
        type:
          type: string
          description: Description of the component.
          example: Database
        status:
          $ref: '#/components/schemas/Status'
    Status:
      type: string
      description: "Status of the component.\n\n- UP: Status indicating that the component or subsystem is functioning as expected.\n- DOWN: Status indicating that the component or subsystem has suffered an unexpected failure.\n- OUT_OF_SERVICE: Status indicating that the component or subsystem has been taken out of service and should not be used.\n- UNKNOWN: Status indicating that the component or subsystem is in an unknown state."
      example: UP
      enum:
        - UP
        - DOWN
        - UNKNOWN
        - OUT_OF_SERVICE
    Health:
      description: Data structure containing information about the health response.
      type: object
      required:
        - status
        - components
      properties:
        status:
          $ref: '#/components/schemas/Status'
        components:
          type: array
          description: List of components.
          items:
            $ref: '#/components/schemas/Component'
  requestBodies:
    CreateEntity:
      description: Request body for new entity operation.
      required: true
      content:
        application/json:
          schema:
            required:
              - id
              - glcs
              - name
              - type
              - industry
              - residenceCountry
              - bookingUnit
              - status
              - sourceApplication
            allOf:
              - $ref: '#/components/schemas/Entity'
    UpdateEntity:
      description: Request body for update entity operation.
      required: true
      content:
        application/json:
          schema:
            required:
              - sourceApplication
              - bookingUnit
            allOf:
              - $ref: '#/components/schemas/Entity'
    CreateAccountOwner:
      description: Request body for new account owner.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountOwner'
    UpdateAccountOwner:
      description: Request body for update account owner.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountOwner'
  responses:
    RetrieveHealth:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Health'
    CreateEntity:
      description: The entity was created successfully.
      content:
        application/json:
          schema:
            required:
              - id
              - glcs
              - name
              - type
              - industry
              - residenceCountry
              - bookingUnit
              - status
              - sourceApplication
            allOf:
              - $ref: '#/components/schemas/Entity'
    UpdateEntity:
      description: The entity was updated successfully.
      content:
        application/json:
          schema:
            required:
              - sourceApplication
              - bookingUnit
            allOf:
              - $ref: '#/components/schemas/Entity'
    CreateAccountOwner:
      description: The account owner was created successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountOwner'
    UpdateAccountOwner:
      description: The account owner was updated successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountOwner'
    RetrieveEntityInformation:
      description: Successful operation.
      content:
        application/json:
          schema:
            required:
              - id
              - glcs
              - name
              - type
              - industry
              - residenceCountry
              - bookingUnit
              - status
              - sourceApplication
            allOf:
              - $ref: '#/components/schemas/Entity'
    TooManyRequests:
      description: Too Many Requests.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: notFound
                message: Not Found
                level: ERROR
                description: Not Found
    NotAcceptable:
      description: Not Acceptable.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: notFound
                message: Not Found
                level: ERROR
                description: Not Found
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: badRequest
                message: Bad Request
                level: ERROR
                description: Bad Request
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: forbidden
                message: Forbidden
                level: ERROR
                description: Forbidden
    GatewayTimeout:
      description: Gateway timeout
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: gatewayTimeout
                message: Gateway timeout
                level: ERROR
                description: Gateway timeout
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: internalServerError
                message: Internal Server Error
                level: ERROR
                description: Internal Server Error
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: notFound
                message: Not Found
                level: ERROR
                description: Not Found
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: serviceUnavailable
                message: Service Unavailable
                level: ERROR
                description: Service Unavailable
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: unauthorized
                message: Unauthorized
                level: ERROR
                description: Unauthorized
    NoContent:
      description: No Content.
  parameters:
    Authorization:
      name: authorization
      in: header
      description: Request header contains the credentials to authenticate a user agent with a server, usually after the server has responded with a 401 Unauthorized status.
      required: true
      schema:
        type: string
    X-Santander-Client-Id:
      name: x-santander-client-id
      in: header
      description: This is the value of the client identifier issued to the client during the application registration process.
      required: true
      schema:
        type: string
    X-Santander-Device:
      name: x-santander-device
      in: header
      required: false
      description: Device information allowed by the operation for data query. Allows to apply base experience to optimize the response according to the device that requests it.
      schema:
        type: string
    Accept-Language:
      name: accept-language
      in: header
      required: false
      description: The consumer defines the list of languages in order of preference. The server responds with the "Content-Language" field in the header with the response language.
      schema:
        type: string
    If-None-Match:
      name: if-none-match
      in: header
      required: false
      description: Gets the GET resources in cache as long as the data of the Etag sent in this header has not changed.
      schema:
        type: string
    If-Match:
      name: if-match
      in: header
      required: false
      description: Used for resource modification requests, this field allows you to make changes only if another client has not made any other changes during execution, that is, if the Etag sent is the same.
      schema:
        type: string
    X-B3-TraceId:
      name: x-b3-traceid
      in: header
      required: false
      description: The X-B3-TraceId header is encoded as 32 or 16 lower-hex characters.
      schema:
        type: string
    X-B3-ParentSpanId:
      name: x-b3-parentspanid
      in: header
      required: false
      description: The X-B3-ParentSpanId header may be present on a child span and must be absent on the root span. It is encoded as 16 lower-hex characters.
      schema:
        type: string
    X-B3-SpanId:
      name: x-b3-spanid
      in: header
      required: false
      description: The X-B3-SpanId header is encoded as 16 lower-hex characters.
      schema:
        type: string
    X-B3-Sampled:
      name: x-b3-sampled
      in: header
      required: false
      description: 'An accept sampling decision is encoded as X-B3-Sampled: 1 and a deny as X-B3-Sampled: 0. Absent means defer the decision to the receiver of this header.'
      schema:
        type: string
    Entity-Glcs:
      name: glcs
      in: query
      required: false
      description: GLCS (Global Limit Code System). Internal and global unique reference of the Legal Entity.
      schema:
        type: string
        maxLength: 6
        example: 'ABC123'
    Markit-Entity-Identifier:
      name: mei
      in: query
      required: false
      description: Markit Entity Identifier (MEI). It's a unique 10-digit code issued to distinctly identify legal entities in the loan market, including banks, buy-side institutions, custodians, trustees and corporate borrowers.
      schema:
        type: string
        maxLength: 10
        example: 'DK0M000104'
    Legal-Entity-Identifier:
      name: lei
      in: query
      required: false
      description: Legal Entity Identifier (LEI). It is a unique global identifier of legal entities participating in financial transactions.
      schema:
        type: string  
        maxLength: 20  
        example: '549300YTPO0S1J7VUG56'
    Entity-Id:
      name: entity_id
      in: path
      required: true
      description: Unique identifier of the operational entity or GLCS (Global Limit Code System).
      schema:
        type: string
        example: '123.28'
  securitySchemes:
    OAuth2-Jwt-Profile:
      description:
        'You can find more information about OAuth2 JWT Profile in our
        confluence: https://confluence.alm.europe.cloudcenter.corp/x/YJDBBg'
      flows:
        implicit:
          authorizationUrl: https://$(auth-security-url)
          scopes:
            gbo-entities.create:
              It is a role that compiles scope of creation on the
              method assigned.
            gbo-entities.delete:
              It is a role that collects deletion scope on the
              assigned method.
            gbo-entities.read:
              It is a role that compiles reading scope on the assigned
              method.
            gbo-entities.update:
              It is a role that collects scope for modification
              of the assigned method.
      type: oauth2
      x-ibm-oauth-provider: scib-oauth-provider
    X-IBM-Client-Id:
      description:
        This is the value of the client identifier issued to the client
        during the application registration process.
      in: header
      name: X-IBM-Client-Id
      type: apiKey
security:
  - OAuth2-Jwt-Profile:
      - gbo-entities.read
      - gbo-entities.create
      - gbo-entities.delete
      - gbo-entities.update
    X-IBM-Client-Id: []
x-ibm-configuration:
  assembly:
    execute:
      - get-properties:
          title: get-properties
          version: 1.0.0
      - jwt-generate-custom:
          aud: $(audience)
          exp-claim: 60
          user: user
          version: 1.1.0
      - switch:
          case:
            - condition: plan.name="live-plan"
              execute:
                - set-variable:
                    actions:
                      - set: target-url
                        type: string
                        value: $(target-url-live)
                    title: set-variable
                    version: 2.0.0
            - otherwise:
                - set-variable:
                    actions:
                      - set: target-url
                        type: string
                        value: $(target-url-sandbox)
                    title: set-variable
                    version: 2.0.0
          title: switch
          version: 2.0.0
      - invoke:
          backend-type: detect
          cache-response: protocol
          cache-ttl: 900
          chunked-uploads: true
          graphql-send-type: detect
          header-control:
            type: blocklist
            values: []
          http-version: HTTP/1.1
          parameter-control:
            type: allowlist
            values: []
          persistent-connection: true
          stop-on-error: []
          target-url: $(target-url)$(api.operation.path)$(request.search)
          timeout: 60
          title: invoke
          verb: keep
          version: 2.2.0
          websocket-upgrade: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    audience:
      description: ''
      encoded: false
      value: $(audience)
    target-url:
      description: ''
      encoded: false
      value: $(target-url)
    target-url-live:
      description: ''
      encoded: false
      value: $(target-url-live)
    target-url-sandbox:
      description: ''
      encoded: false
      value: $(target-url-sandbox)
  type: rest
